#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx git-pull-run -p "pnpm-lock.yaml" -c "pnpm install"

if git diff --name-only ORIG_HEAD HEAD | grep -q "prisma/migrations"; then
  echo "🧱 Prisma migrations changed — running migrate..."
  npx prisma migrate dev
else
  echo "✅ No migration changes detected."
fi